export const SHOE_CONSTANT = {
  GET_SHOE_LIST: 'GET_SHOE_LIST',
  SET_SHOE_LIST: 'SET_SHOE_LIST',
  SET_SHOE_LIST_ERROR: 'SET_SHOE_LISt_ERROR',
  GET_SHOE_LIST_ID: 'GET_SHOE_LIST_ID',
  SET_SHOE_LIST_ID: 'SET_SHOE_LIST_ID',
  GET_SHOE_INFO: 'GET_SHOE_INFO',
  SET_SHOE_INFO: 'SET_SHOE_INFO',
  GET_SHOE_INFO_ERROR: 'GET_SHOE_INFO_ERROR',
};
